# CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id gpt-4-1106-vision-preview --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
# CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id gemini-pro-vision --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id claude-3-sonnet-20240229 --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id qwen-vl-plus --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id minigpt-4-llama2-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id minigpt-4-vicuna-13b-v0 --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id llava-v1.5-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id llava-v1.5-13b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id llava-v1.6-13b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id ShareGPT4V-13B --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id llava-rlhf-13b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id LVIS-Instruct4V --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id otter-mpt-7b-chat --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id internlm-xcomposer-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id internlm-xcomposer2-vl-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id mplug-owl-llama-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id mplug-owl2-llama2-7b --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id InternVL-Chat-ViT-6B-Vicuna-13B --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id instructblip-flan-t5-xxl --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id qwen-vl-chat --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
CUDA_VISIBLE_DEVICES=3 python test_run_single_model.py --task g-text-none --model_id cogvlm-chat-hf --output_dir /data/zhangyichi/Trustworthy-MLLM/output/truthfulness/text/plain_text
