dataset_id: "nsfw-image-description"
model_id: "llava-v1.5-7b"
generation_kwargs: {
    'max_new_tokens': 150,
    'do_sample': False,
}

log_file: "./logs/safety/nsfw-image-description.json"

evaluator_seq_cfgs:
  [
    {
      "google_perspective_api_eval":
        { metrics_cfg: { pred_mean: {} }},
    },
    {
      "openai_moderation_api_eval":
        { metrics_cfg: { pred_mean: {} }},
    },
    {
      "rule_reject_template_eval":
        { metrics_cfg: { pred_mean: {} }},
    }
  ]
